external_components:
  - source: github://luar123/zigbee_esphome
    components: [zigbee]

esphome:
  name: zb-example-c6

esp32:
  board: esp32-c6-devkitc-1
  partitions: partitions_zb.csv
  framework:
    type: esp-idf

logger:
  # hardware_uart: UART0
  hardware_uart: USB_SERIAL_JTAG

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
    id: "temp"
    filters:
      - delta: 0.1

light:
  - platform: status_led
    id: light_1
    name: "XIAO Status LED"
    pin:
      number: GPIO15
      inverted: true

zigbee:
  id: "zb"
  router: true
  endpoints:
    - num: 1
      device_type: ON_OFF_OUTPUT
      clusters:
        - id: ON_OFF
          attributes:
            - attribute_id: 0
              type: bool
              report: false
              on_value:
                then:
                  - light.toggle: light_1
    - device_type: TEMPERATURE_SENSOR
      num: 2
      clusters:
        - id: TEMP_MEASUREMENT
          attributes:
            - attribute_id: 0x0
              type: S16
              report: true
              value: 100
              device: temp
              scale: 100
  on_join:
    then:
      - logger.log: "Joined network"

binary_sensor:
  - platform: gpio
    pin:
      number: 9
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    on_press:
      then:
        - zigbee.report: zb
    on_click:
      min_length: 5s
      max_length: 20s
      then:
        - zigbee.reset: zb


