substitutions:
  device_name: temperature

esphome:
  name: ${device_name}-esphome

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf

# Enable logging
logger:

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .lan

mqtt:
  broker: ops.lan
  port: 1883
  discovery: true
  discovery_retain: true
  discovery_unique_id_generator: mac
  birth_message:
    topic: ${device_name}/status
    payload: online
  will_message:
    topic: ${device_name}/status
    payload: offline

light:
  - platform: binary
    name: "WiFi Status LED"
    id: wifi_led
    output: led_output
    internal: true

output:
  - platform: gpio
    pin: GPIO2  # Change this to your LED pin
    id: led_output

# WiFi connection status automation.
interval:
  - interval: 5s
    then:
      - if:
          condition:
            wifi.connected:
          then:
            - light.turn_off: wifi_led
          else:
            - light.turn_on: wifi_led
 
one_wire:
  - platform: gpio
    pin: GPIO18

sensor:
  - platform: dallas_temp
    name: Temperature
    update_interval: 10s
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1
    expire_after: 30s

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO25
      mode:
        input: true
        pullup: true
      inverted: true  # Motion occurs when signal goes LOW
    name: "Motion Detected"
    id: motion_sensor
    device_class: motion
    filters:
      - delayed_on: 50ms
      - delayed_off: 3s
    on_press:
      then:
        - logger.log: "Motion detected!"
    on_release:
      then:
        - logger.log: "Motion cleared"

remote_transmitter:
  pin: GPIO4  # Change to your actual transmitter pin
  carrier_duty_percent: 100%

globals:
  - id: binary_code
    type: std::string
    initial_value: '""'
  - id: binary_codes
    type: std::vector<std::string>
    restore_value: no

script:
  - id: codes_to_binary
    parameters:
      codes: string
    then:
      - lambda: |-
          // Clear previous codes
          id(binary_codes).clear();
          
          // Parse comma-separated string
          std::string codes_str = codes;
          std::string delimiter = ",";
          size_t pos = 0;
          std::string token;
          
          // Add trailing comma to catch last element
          codes_str += ",";
          
          while ((pos = codes_str.find(delimiter)) != std::string::npos) {
            token = codes_str.substr(0, pos);
            
            // Trim whitespace
            token.erase(0, token.find_first_not_of(" \t"));
            token.erase(token.find_last_not_of(" \t") + 1);
            
            if (!token.empty() && token[0] == '{') {
              // Parse format: {bits}code
              size_t close_brace = token.find('}');
              if (close_brace != std::string::npos) {
                std::string bits_str = token.substr(1, close_brace - 1);
                int bit_count = std::stoi(bits_str);
                std::string code_str = token.substr(close_brace + 1);
                
                // Parse hex code (assume hex without 0x prefix)  
                uint64_t parsed_code = std::stoull(code_str, nullptr, 16);
                
                // Find how many bits this code naturally has
                int natural_bits = 64 - __builtin_clzll(parsed_code);
                
                uint64_t code;
                if (natural_bits > bit_count) {
                  // Shift right to align properly
                  int shift = natural_bits - bit_count + 1;
                  code = parsed_code >> shift;
                  // Mask to ensure we only use the specified bit count
                  uint64_t mask = (1ULL << bit_count) - 1;
                  code = code & mask;
                } else {
                  code = parsed_code;
                }
                
                // Convert to binary string and apply inverse logic
                std::string binary = "";
                for (int i = bit_count - 1; i >= 0; i--) {
                  bool bit = (code >> i) & 1;
                  binary += bit ? "0" : "1";  // Apply inverse logic
                }
                
                // Store in global vector
                id(binary_codes).push_back(binary);

                // Log for debugging
                ESP_LOGD("transmit_codes", "Code: %s, Bits: %d, Parsed: 0x%llx, Binary: %s", 
                         code_str.c_str(), bit_count, code, binary.c_str());
              }
            }
            
            codes_str.erase(0, pos + delimiter.length());
          }
      - repeat:
          count: !lambda "return id(binary_codes).size();"
          then:
            - remote_transmitter.transmit_rc_switch_raw:
                code: !lambda "return id(binary_codes)[iteration];"
                protocol:
                  pulse_length: 104
                  sync: [1, 116]
                  zero: [4, 12]
                  one: [12, 4]
  - id: transmit_house_code
    parameters:
      house: int
      code: int
    then:
      - lambda: |-
          // Use uint32_t to ensure we have enough bits
          uint32_t combined = ((uint32_t)house << 8) | (uint32_t)code;
          
          // Convert to 24-bit binary string
          std::string binary_str = "";
          for (int i = 23; i >= 0; i--) {
            if (combined & (1UL << i)) {
              binary_str += "1";
            } else {
              binary_str += "0";
            }
          }
          
          ESP_LOGD("house_code", "House: %d, Code: %d -> Combined: %lu -> Binary: %s", 
                   house, code, (unsigned long)combined, binary_str.c_str());
          
          id(binary_code) = binary_str;
      - remote_transmitter.transmit_rc_switch_raw:
          code: !lambda "return id(binary_code);"
          protocol:
            pulse_length: 400
            sync: [1, 31]
            zero: [1, 3]
            one: [3, 1]
          repeat:
            times: 5
            wait_time: 0s

button:
  - platform: template
    name: "Living Room Light Toggle"  
    id: ${device_name}_ceiling_fan_light_toggle
    on_press:
      - script.execute:
          id: codes_to_binary
          codes: '{32}d1eff8c7, {33}68f7fc638, {33}68f7fc638'
          # 00101110000100000000011100111000, 100101110000100000000011100111000, 100101110000100000000011100111000
  - platform: template
    name: "Bedroom 2 Light On"
    id: ${device_name}_ceiling_fan_light_on
    on_press:
      - script.execute:
          id: transmit_house_code
          house: 13785
          code: 4
  - platform: template
    name: "Bedroom 2 Light Off"
    id: ${device_name}_ceiling_fan_light_off
    on_press:
      - script.execute:
          id: transmit_house_code
          house: 13785
          code: 1
  - platform: template
    name: "Bedroom 1 Light On"
    on_press:
      - script.execute:
          id: transmit_house_code
          house: 63258
          code: 4
  - platform: template
    name: "Bedroom 2 Light Off"
    on_press:
      - script.execute:
          id: transmit_house_code
          house: 63258
          code: 1

