substitutions:
  device_name: coordinator

esphome:
  name: ${device_name}-esphome

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf

# Enable logging
logger:

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .lan

light:
  - platform: binary
    name: "WiFi Status LED"
    id: wifi_led
    output: led_output
    internal: true

output:
  - platform: gpio
    pin: GPIO2  # Change this to your LED pin
    id: led_output

# WiFi connection status automation.
interval:
  - interval: 5s
    then:
      - if:
          condition:
            wifi.connected:
          then:
            - light.turn_off: wifi_led
          else:
            - light.turn_on: wifi_led
 
##########################################

uart:
  id: uart_bus
  tx_pin: GPIO12
  rx_pin: GPIO13
  baud_rate: 115200

external_components:
  - source:
      type: local
      path: components
serial_bridge:
  uart_id: uart_bus
  port: 8888
