substitutions:
  device_name: particles

external_components:
  - source: github://luar123/zigbee_esphome
    components: [zigbee]

esphome:
  name: ${device_name}-esphome

esp32:
  board: esp32-c6-devkitc-1
  partitions: partitions_zb.csv
  framework:
    type: esp-idf

logger:
  # hardware_uart: UART0
  hardware_uart: USB_SERIAL_JTAG

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
    id: "internal_temp"
    filters:
      - delta: 0.1
    update_interval: 5min
  - platform: hm3301
    pm_1_0:
      name: "PM1.0"
      id: pm1
    pm_2_5:
      name: "PM2.5"
      id: pm25
    pm_10_0:
      name: "PM10.0"
      id: pm10
      on_value:
        then:
          - if:
              condition:
                lambda: 'return x <= 10.0;'
              then:
                - light.turn_off:
                    id: light_1
              else:
                - light.turn_on:
                    id: light_1
    aqi:
      name: "AQI"
      calculation_type: "CAQI"
      id: aqi
    update_interval: 5min
  - platform: aht10
    variant: AHT20
    temperature:
      name: "Temperature"
      id: "temperature"
      filters:
        - delta: 0.1
    update_interval: 5min
    humidity:
      name: "Humidity"
      id: "humidity"
      filters:
        - delta: 0.5
    update_interval: 15min

i2c:
  sda: GPIO22
  scl: GPIO23

light:
  - platform: status_led
    id: light_1
    name: "XIAO Status LED"
    pin:
      number: GPIO15
      inverted: true


globals:
  - id: color_x
    type: float
    restore_value: no
    initial_value: '0'
  - id: color_y
    type: float
    restore_value: no
    initial_value: '0'

zigbee:
  id: "zb"
  router: true
  endpoints:
    - device_type: TEMPERATURE_SENSOR
      num: 1
      clusters:
        - id: TEMP_MEASUREMENT
          attributes:
            - attribute_id: 0x0
              type: S16
              report: true
              value: 100
              device: temperature
              scale: 100
        - id: REL_HUMIDITY_MEASUREMENT
          attributes:
            - attribute_id: 0x0
              type: S16
              report: true
              value: 100
              device: humidity
              scale: 100
    - device_type: TEMPERATURE_SENSOR
      num: 2
      clusters:
        - id: TEMP_MEASUREMENT
          attributes:
            - attribute_id: 0x0
              type: S16
              report: true
              value: 100
              device: internal_temp
              scale: 100
    - num: 3
      device_type: SIMPLE_SENSOR
      clusters:
        - id: PM2_5_MEASUREMENT
          attributes:
            - attribute_id: 0x0
              type: single
              report: true
              value: 0
              device: pm25
            - attribute_id: 0x2 # maximum value is needed!
              type: single
              value: 999
    - num: 4
      device_type: SIMPLE_SENSOR
      clusters:
        - id: ANALOG_INPUT
          attributes:
            - attribute_id: 0x001C
              type: CHAR_STRING
              max_length: 3    #  This needs to match character count of value below
              report: true
              value: PM1
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: single
              report: true
              value: 0
              device: pm1    #  Sensor ID defined earlier in your ESPHome config
            - attribute_id: 0x0075
              type: 16BIT_ENUM
              value: 219     # μg/m³ (most common for PM measurements)
              report: true
            - attribute_id: 0x006F
              type: 8BITMAP
              value: 0
    - num: 5
      device_type: SIMPLE_SENSOR
      clusters:
        - id: ANALOG_INPUT
          attributes:
            - attribute_id: 0x001C
              type: CHAR_STRING
              max_length: 4    #  This needs to match character count of value below
              report: true
              value: PM10
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: single
              report: true
              value: 0
              device: pm10    #  Sensor ID defined earlier in your ESPHome config
            - attribute_id: 0x0075
              type: 16BIT_ENUM
              value: 219     # μg/m³ (most common for PM measurements)
              report: true
            - attribute_id: 0x006F
              type: 8BITMAP
              value: 0

    - num: 6
      device_type: SIMPLE_SENSOR
      clusters:
        - id: ANALOG_INPUT
          attributes:
            - attribute_id: 0x001C
              type: CHAR_STRING
              max_length: 5    #  This needs to match character count of value below
              report: true
              value: PM2.5
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: single
              report: true
              value: 0
              device: aqi
            - attribute_id: 0x006F
              type: 8BITMAP
              value: 0

  on_join:
    then:
      - logger.log: "Joined network"
      - light.turn_on: light_1


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO9  # Boot button on ESP32-C6-DevKitC-1
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Boot Button"
    id: boot_button
    on_click:
      min_length: 1s
      max_length: 20s
      then:
        - logger.log: "Boot button long press - resetting Zigbee to rejoin"
        - light.turn_on: light_1
        - delay: 100ms
        - light.turn_off: light_1
        - delay: 100ms
        - light.turn_on: light_1
        - delay: 100ms
        - light.turn_off: light_1
        - zigbee.reset:
            id: zb
